# Remote node_exporter via Tailscale MagicDNS (port 9100).
- targets:
    - streamrtn1.taild08b87.ts.net:9100
  labels:
    instance: streamrtn1
- targets:
    - streamrtn2.taild08b87.ts.net:9100
  labels:
    instance: streamrtn2
- targets:
    - streamrtn3.taild08b87.ts.net:9100
  labels:
    instance: streamrtn3
- targets:
    - streamrtn4.taild08b87.ts.net:9100
  labels:
    instance: streamrtn4
